name: flutter_create
description: For creating custom flutter project from template. A standalone solution to issue https://github.com/flutter/flutter/issues/15279
version: 1.0.0
homepage: https://github.com/odunboye/flutter_create

environment:
  sdk: '>=2.7.0 <3.0.0'


executables:
  flutter_create:

dependencies:
 path: ^1.6.4
 rename: ^1.1.9
  
 args: ^1.5.2

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
 
